### ISSUE TITLE
Add reference to templating format in README

### ISSUE THREAD

**Issue by whitty** [tomasbjerre/violation-comments-lib#10]
I might be a bit thick (or at least not Java-y enough - I'm and embedded C/C++ guy :-) - so I was trying to find a reference for the templating language you have used, but didn't come up with anything.

If this is a well-known or third party library could you provide a link?

Specifically there are "/" and "#" prefixes on some substitutions - I'm sure if I had the right background I'd recognise them immediately and I can take some guesses as to what they do.

**Comment by tomasbjerre** [comment]
It is Mustache https://github.com/spullara/mustache.java

Updated the readme with this.
