### ISSUE TITLE
Remove carriage return

### ISSUE THREAD

**Issue by kduret** [tomasbjerre/violation-comments-lib#13]
Hi,

Is it possible to remove the carriage return between violation template and fingerprint ?
Cause it adds useless empty lines in github comments

![image](https://user-images.githubusercontent.com/11978823/63921021-4fface80-ca42-11e9-9bff-541549efb722.png)

**Comment by tomasbjerre** [comment]
Should be released in all the Github tools now.

**Comment by kduret** [comment]
great! thanks for your job :)
