### ISSUE TITLE
Wrong Line number being commented

### ISSUE THREAD

**Issue by AlteaDown** [tomasbjerre/violation-comments-lib#15]
I'm noticing for Single File Comments, the wrong line numbers are being commented. I've attached the output with debugging info here:
[commandOutput.txt](https://github.com/tomasbjerre/violation-comments-lib/files/4140533/commandOutput.txt)

As an example, on LoginScreen.tsx it should comment on line 125 and 163, but it instead comments on line 1.

I've also attached the eslint_report.xml file (in CHECKSTYLE) used for this here (note, it was a .xml before uploading): 
[eslint_report.txt](https://github.com/tomasbjerre/violation-comments-lib/files/4140547/eslint_report.txt)

And an example diff that has the issue:

[exampleDiff.txt](https://github.com/tomasbjerre/violation-comments-lib/files/4140549/exampleDiff.txt)

**Comment by tomasbjerre** [comment]
Happens here:
https://github.com/tomasbjerre/violation-comments-to-bitbucket-cloud-lib/blob/master/src/main/java/se/bjurr/violations/comments/bitbucketcloud/lib/BitbucketCloudCommentsProvider.java#L69

Which means the lib was unable to parse the diff to find the corresponding line number in the diff. The line number that needs to be used when creating the comment...

I'm not sure it can be done differently, pull requests are welcome.

**Comment by tomasbjerre** [comment]
Also reported here: https://github.com/tomasbjerre/violation-comments-to-bitbucket-cloud-lib/issues/4
