### ISSUE TITLE
Violation message configuration feature request

### ISSUE THREAD

**Issue by andye2004** [tomasbjerre/violation-comments-lib#2]
Hi @tomasbjerre, I'm just doing some testing with your library now and my initial thoughts are that it is really good. However, I find the comments generated to be a little verbose and I was wondering about the possibility of a feature enhancement to structure the comments differently and make them a little more concise?

I've only been looking at the Checkstyle parser from the maven plugin but tracked the comments back to CommentsCreator in this library, hence the reason I'm raising the issue here.

I'm sure I don't need to illustrate the comments to you but we currently have this:

> Reporter: Checkstyle
Rule: com.puppycrawl.tools.checkstyle.checks.blocks.LeftCurlyCheck
Severity: WARN
File: src/main/java/com/yambay/InvalidStyleClass.java L4
> 
> '{' at column 1 should be on the previous line.
> 
> <1284013061>

When we would ideally like something more like:

> Reporter: Checkstyle
'{' at column 1 should be on the previous line.

or maybe even just:

> '{' at column 1 should be on the previous line.

Could probably be done via configuration by specifying something like:

```xml
<ViolationComment>
  <includes>
    <include>VIOLATION_MESSAGE</include>
  </includes>
</ViolationComment>
```
Or alternatively an excludes block if we were looking to just drop lets say the filename maybe?

**Comment by tomasbjerre** [comment]
You don't want to include the file, and line, at all?

**Comment by andye2004** [comment]
The way I see it, the comment is being written directly under the offending line so it should be obvious where the problem lies. I'm guessing that 'createSingleFileComments' is set to false you would need to add the file name and line number even if they were not included in the config.

**Comment by tomasbjerre** [comment]
Ok I see...

Perhaps it can be a small template.

```
<violationCommentTemplate>
<![CDATA[
Reporter: $violation.reporter
Rule: $violation.rule
Severity: $violation.severity
...
]]>
</violationCommentTemplate>
```

**Comment by andye2004** [comment]
Sounds great Tomas

**Comment by mjurkus** [comment]
Would it be possible to have `fileName` param for event shorter comments?

```
File: InvalidStyleClass.kt:3:18
```

This would allow copy and paste to IDEA file search with jump to specific location in the file.

**Comment by tomasbjerre** [comment]
Custom template is now supported. See readme.

@mjurkus That will soon be released. There will be `fileName` that resolves to just the name and `file` that resolves to the full path.
