### ISSUE TITLE
Please add option to limit number of comments

### ISSUE THREAD

**Issue by congtq** [tomasbjerre/violation-comments-lib#8]
Thanks for greate lib.

I've a project which has very bad format that caused 1000+ comments. When Jenkins posts comments to GitLab it consumes very long time and to much comments on GitLab. That makes it very hard to view.  
In order to avoid that, I want an option `Max comments number` (or somthing like that) that accepts integer value. When specified an integer value, it will limit number of comments to that value.  
Please consider about this enhancment!

**Comment by tomasbjerre** [comment]
Releasing this now as version 2.24 of the Gitlab plugin. Open issue again if not working!
